widgetTheme=widget-themes/original
primaryColor=#41b8ee
secondaryColor=#41b8ee
labelColor=#ffffff
hideWhenOffline=false
contactMail=help@ogut.am
loadingLabel=Loading...
loginError=Login error
chatHeader=Գրեք մեզ
startInfo=Խնդրում ենք լրացնել հետևյալ դաշտերը
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Սկսել
backLabel=Վերադառնալ
initMessageBody=Ողջու՜յն։ Ինչո՞վ կարող եմ ձեզ օգնել։
initMessageAuthor=Օգնական
chatInputLabel=Գրեք ձեր հարցը
timeDaysAgo=օր առաջ
timeHoursAgo=ժամ առաջ
timeMinutesAgo=րոպե առաջ
timeSecondsAgo=վայրկայն առաջ
offlineMessage=Օգնականը կայքում չէ
toggleSoundLabel=voice
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=Ավարտել չաթը
endChatConfirmQuestion=Վստա՞հ եք
endChatConfirm=Այո
endChatCancel=Չեղարկել
contactHeader=Հետադարձ կապ
contactInfo=Այժմ մենք տեղում չենք։ Թողե՜ք ձեր հարցը և մենք հնարավորինս արագ կպատասխանենք ձեզ։
contactNameLabel=Ձեր անունը
contactMailLabel=Ձեր էլ․ հասցեն
contactQuestionLabel=Ձեր հարցը
contactSendLabel=Ուղարկել
contactSuccessHeader=Հաղորդագրությունն ուղարկված է
contactSuccessMessage=Ձեր հարցը ուղարկված է։ Շնորհակալություն
contactErrorHeader=Սխալ
contactErrorMessage=Հաղորդագրությունն ուղարկելու ընթացքում տեղի ունեցավ սխալ
headerHeight=55
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
